default: &default
 host: localhost
 port: 3306
 user: root
 password: Srams6711!
 adapter: mysql

development:
 <<: *default
 db: application_database_name_development

test:
 <<: *default
 db: application_database_name_test

production:
 <<: *default
 db: application_database_name_production